# Generated by Django 4.1.3 on 2022-11-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ph_num',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
