# Generated by Django 4.1.3 on 2022-11-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_msg_alter_person_ph_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='msg',
            field=models.CharField(default='', max_length=100),
        ),
    ]
