# Generated by Django 4.1.3 on 2022-11-11 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_person_msg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='msg',
        ),
    ]
